In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

 Metadata Inspection:

In [3]:
import pandas as pd

from src.inspection.metadata import MetadataInspector

In [4]:
customers = pd.read_csv("../data/raw/olist/olist_customers_dataset.csv")

In [5]:
metadata = MetadataInspector(customers)

In [6]:
results = metadata.inspect()

In [7]:
results["dataset"]

{'rows': 99441, 'columns': 5, 'shape': (99441, 5)}

In [8]:
results["memory"]

{'memory_bytes': 27877866,
 'memory_mb': np.float64(26.59),
 'average_row_bytes': np.float64(280.35)}

In [9]:
results["columns"]

{'column_count': 5,
 'column_names': ['customer_id',
  'customer_unique_id',
  'customer_zip_code_prefix',
  'customer_city',
  'customer_state']}

In [10]:
results["schema"]

   position                    column  dtype
0         0               customer_id    str
1         1        customer_unique_id    str
2         2  customer_zip_code_prefix  int64
3         3             customer_city    str
4         4            customer_state    str

In [11]:
results["sample"]["head"]

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [12]:
results["sample"]["tail"]

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [13]:
results["sample"]["random"]

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
52263,c7432c6d237ffd6aa36a007b4237ec38,9a897ea48bf988012c00b802f1104a92,2971,sao paulo,SP
46645,7f399d641e2e2064470145178c9e8778,90436a67885a57f147fb79e6d0e4bc1c,38610,unai,MG
37546,ba5642b730704dc0f74b7cf715b41ed5,4d8056f71519ae1069e6747c63c676f7,88820,icara,SC
94756,0f346a2cc84ebb2d52f0759d0acfd030,6117c9ef3251089693a6abb90c195eba,25250,duque de caxias,RJ
14771,d393b9491df482cf448e60aa9955b7f2,5caf3a2a5d1ef808e3dd182e79baa392,36955,mutum,MG

Schema Validation:

In [6]:
import pandas as pd

from src.inspection.schema_validation import SchemaValidator

In [7]:
customers = pd.read_csv("../data/raw/olist/olist_customers_dataset.csv")

In [8]:
validator = SchemaValidator(customers)

results = validator.validate()

In [9]:
results["schema"]

                     column  dtype semantic_type matches_expected_dtype
0               customer_id    str          Text                   None
1        customer_unique_id    str          Text                   None
2  customer_zip_code_prefix  int64       Numeric                   None
3             customer_city    str          Text                   None
4            customer_state    str          Text                   None

In [10]:
results["datetime_columns"]

[]

In [11]:
results["summary"]

{'total_columns': 5, 'semantic_type_distribution': {'Text': 4, 'Numeric': 1}}

In [12]:
expected_schema = {
    "customer_id": "object",
    "customer_unique_id": "object",
    "customer_zip_code_prefix": "int64",
    "customer_city": "object",
    "customer_state": "object"
}

In [13]:
validator = SchemaValidator(
    customers,
    expected_schema=expected_schema
)

results = validator.validate()

In [14]:
results["expected_schema"]

{'missing_columns': [],
 'unexpected_columns': [],
 'dtype_mismatches': {'customer_id': {'expected': 'object', 'actual': 'str'},
  'customer_unique_id': {'expected': 'object', 'actual': 'str'},
  'customer_city': {'expected': 'object', 'actual': 'str'},
  'customer_state': {'expected': 'object', 'actual': 'str'}},
 'schema_match': False}

In [15]:
expected_schema = {
    "customer_id": "string",
    "customer_unique_id": "object",
    "customer_zip_code_prefix": "float64",
    "customer_city": "object",
    "customer_state": "object"
}

In [16]:
validator = SchemaValidator(
    customers,
    expected_schema
)

results = validator.validate()

In [17]:
results["expected_schema"]

{'missing_columns': [],
 'unexpected_columns': [],
 'dtype_mismatches': {'customer_id': {'expected': 'string', 'actual': 'str'},
  'customer_unique_id': {'expected': 'object', 'actual': 'str'},
  'customer_zip_code_prefix': {'expected': 'float64', 'actual': 'int64'},
  'customer_city': {'expected': 'object', 'actual': 'str'},
  'customer_state': {'expected': 'object', 'actual': 'str'}},
 'schema_match': False}

Data Quality Inspection:

In [19]:
import pandas as pd

from src.inspection.data_quality import DataQualityInspector

In [20]:
customers = pd.read_csv("../data/raw/olist/olist_customers_dataset.csv")

In [21]:
customers.shape

(99441, 5)

In [22]:
inspector = DataQualityInspector(
    dataframe=customers,
    primary_keys=["customer_id"]
)

In [23]:
results = inspector.inspect()

In [24]:
results["missing_values"]

                          missing_count  missing_percent
customer_id                           0              0.0
customer_unique_id                    0              0.0
customer_zip_code_prefix              0              0.0
customer_city                         0              0.0
customer_state                        0              0.0

In [25]:
results["duplicates"]

{'duplicate_rows': 0, 'duplicate_percentage': 0.0, 'duplicate_primary_keys': 0}

In [26]:
results["uniqueness"]

                     column  unique_values  cardinality  candidate_key
0               customer_id          99441       1.0000           True
1        customer_unique_id          96096       0.9664          False
2  customer_zip_code_prefix          14994       0.1508          False
3             customer_city           4119       0.0414          False
4            customer_state             27       0.0003          False

In [27]:
results["blank_values"]

{'customer_id': 0,
 'customer_unique_id': 0,
 'customer_city': 0,
 'customer_state': 0}

In [28]:
results["constant_columns"]

[]

In [29]:
results["completeness"]

{'total_cells': 497205,
 'non_missing_cells': 497205,
 'dataset_completeness': np.float64(100.0)}

In [30]:
results["quality_score"]

np.float64(100.0)

In [31]:
results["summary"]

{'rows': 99441,
 'columns': 5,
 'constant_columns': 0,
 'quality_score': np.float64(100.0)}

Sample data record to test the script under uncertainity.

In [32]:
test_df = customers.copy()

# Introducing a missing value
test_df.loc[0, "customer_city"] = None

# Introducing a duplicate row
test_df = pd.concat(
    [test_df, test_df.iloc[[0]]],
    ignore_index=True
)

# Introducing a blank string
test_df.loc[1, "customer_state"] = "   "

In [33]:
inspector = DataQualityInspector(
    test_df,
    primary_keys=["customer_id"]
)

results = inspector.inspect()

In [34]:
results["missing_values"]

                          missing_count  missing_percent
customer_id                           0              0.0
customer_unique_id                    0              0.0
customer_zip_code_prefix              0              0.0
customer_city                         2              0.0
customer_state                        0              0.0

In [35]:
results["duplicates"]

{'duplicate_rows': 1, 'duplicate_percentage': 0.0, 'duplicate_primary_keys': 1}

In [36]:
results["blank_values"]

{'customer_id': 0,
 'customer_unique_id': 0,
 'customer_city': 0,
 'customer_state': 1}

The validator is performing quality checks as expected.

Descriptive statistics of customers:

In [2]:
import pandas as pd

from src.inspection.descriptive_statistics import DescriptiveStatistics

In [3]:
customers = pd.read_csv("../data/raw/olist/olist_customers_dataset.csv")

In [4]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [5]:
profiler = DescriptiveStatistics(customers)

In [6]:
results = profiler.profile()

In [7]:
results["summary"]

{'total_columns': 5,
 'numeric_columns': 1,
 'categorical_columns': 4,
 'boolean_columns': 0}

In [8]:
results["numeric"]

,column,dtype,count,missing,unique,mean,median,mode,minimum,maximum,range,variance,std_dev,coefficient_variation,q1,q2,q3,iqr,skewness,kurtosis
0,customer_zip_code_prefix,int64,99441,0,14994,35137.474583,24416.0,22790,1003,99990,98987,8.879172e+08,29797.938996,0.848039,11347.0,24416.0,58900.0,47553.0,0.779025,-0.788204

In [9]:
results["categorical"]

,column,dtype,count,missing,unique,cardinality,most_frequent,frequency,top_categories
0,customer_id,str,99441,0,99441,1.0000,00012a2ce6f8dcda20d059ce98491703,1,"{'06b8999e2fba1a1fbc88172c00ba8bc7': 1, '18955..."
1,customer_unique_id,str,99441,0,96096,0.9664,8d50f5eadf50201ccdcedfb9e2ac8455,17,"{'8d50f5eadf50201ccdcedfb9e2ac8455': 17, '3e43..."
2,customer_city,str,99441,0,4119,0.0414,sao paulo,15540,"{'sao paulo': 15540, 'rio de janeiro': 6882, '..."
3,customer_state,str,99441,0,27,0.0003,SP,41746,"{'SP': 41746, 'RJ': 12852, 'MG': 11635, 'RS': ..."

In [10]:
results["categorical"]["top_categories"]

0    {'06b8999e2fba1a1fbc88172c00ba8bc7': 1, '18955...
1    {'8d50f5eadf50201ccdcedfb9e2ac8455': 17, '3e43...
2    {'sao paulo': 15540, 'rio de janeiro': 6882, '...
3    {'SP': 41746, 'RJ': 12852, 'MG': 11635, 'RS': ...
Name: top_categories, dtype: object

In [11]:
results["categorical"].query("column == 'customer_id'")

,column,dtype,count,missing,unique,cardinality,most_frequent,frequency,top_categories
0,customer_id,str,99441,0,99441,1.0,00012a2ce6f8dcda20d059ce98491703,1,"{'06b8999e2fba1a1fbc88172c00ba8bc7': 1, '18955..."

In [12]:
results["categorical"].query("column == 'customer_unique_id'")

,column,dtype,count,missing,unique,cardinality,most_frequent,frequency,top_categories
1,customer_unique_id,str,99441,0,96096,0.9664,8d50f5eadf50201ccdcedfb9e2ac8455,17,"{'8d50f5eadf50201ccdcedfb9e2ac8455': 17, '3e43..."

In [13]:
customers.describe(include="number")

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [14]:
customers.describe(include="object")

C:\Users\sufiy\AppData\Local\Temp\ipykernel_18940\1913638412.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  customers.describe(include="object")

,customer_id,customer_unique_id,customer_city,customer_state
count,99441,99441,99441,99441
unique,99441,96096,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,sao paulo,SP
freq,1,17,15540,41746

Testing the descriptive statistics script on edge cases

In [15]:
test_df = customers.copy()

# Constant numeric column
test_df["constant_numeric"] = 100

# Constant categorical column
test_df["constant_category"] = "A"

# Numeric column with missing values
test_df.loc[:100, "customer_zip_code_prefix"] = None

# Column with a single repeated category
test_df["single_value"] = "TEST"

In [16]:
profiler = DescriptiveStatistics(test_df)
results = profiler.profile()

In [17]:
results["categorical"]

,column,dtype,count,missing,unique,cardinality,most_frequent,frequency,top_categories
0,customer_id,str,99441,0,99441,1.0000,00012a2ce6f8dcda20d059ce98491703,1,"{'06b8999e2fba1a1fbc88172c00ba8bc7': 1, '18955..."
1,customer_unique_id,str,99441,0,96096,0.9664,8d50f5eadf50201ccdcedfb9e2ac8455,17,"{'8d50f5eadf50201ccdcedfb9e2ac8455': 17, '3e43..."
2,customer_city,str,99441,0,4119,0.0414,sao paulo,15540,"{'sao paulo': 15540, 'rio de janeiro': 6882, '..."
3,customer_state,str,99441,0,27,0.0003,SP,41746,"{'SP': 41746, 'RJ': 12852, 'MG': 11635, 'RS': ..."
4,constant_category,str,99441,0,1,0.0000,A,99441,{'A': 99441}
5,single_value,str,99441,0,1,0.0000,TEST,99441,{'TEST': 99441}

In [18]:
results["numeric"]

,column,dtype,count,missing,unique,mean,median,mode,minimum,maximum,range,variance,std_dev,coefficient_variation,q1,q2,q3,iqr,skewness,kurtosis
0,customer_zip_code_prefix,float64,99340,101,14992,35138.838665,24416.0,22790.0,1003.0,99990.0,98987.0,8.878987e+08,29797.629258,0.847997,11349.5,24416.0,58900.0,47550.5,0.779011,-0.788143
1,constant_numeric,int64,99441,0,1,100.000000,100.0,100.0,100.0,100.0,0.0,0.000000e+00,0.000000,0.000000,100.0,100.0,100.0,0.0,0.000000,0.000000

In [19]:
results["summary"]

{'total_columns': 8,
 'numeric_columns': 2,
 'categorical_columns': 6,
 'boolean_columns': 0}

The script adapts to uncertainty.